show tables where Tables_in_Facturacion='proveedor';
desc proveedor;
show tables where Tables_in_Facturacion='producto';
desc producto;
show tables where Tables_in_Facturacion='grupos';
desc grupos;
show tables where Tables_in_Facturacion='cliente';
desc cliente;
show tables where Tables_in_Facturacion='empleado';
desc empleado;
show tables where Tables_in_Facturacion='item';
desc item;
show tables where Tables_in_Facturacion='gastos';
desc gastos;
show tables where Tables_in_Facturacion='factura';
desc factura;
show tables where Tables_in_Facturacion='proveedor_producto';
desc proveedor_producto;
show tables where Tables_in_Facturacion='producto_grupos';
desc producto_grupos;
show tables where Tables_in_Facturacion='producto_factura';
desc producto_factura;
show tables where Tables_in_Facturacion='telefonos_cliente';
desc telefonos_cliente;
show tables where Tables_in_Facturacion='item_gastos';
desc item_gastos;
show tables where Tables_in_Facturacion='telefono_proveedor';
desc telefono_proveedor;